version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432" # Mapeia a porta 5432 no host para a porta 5432 no contêiner
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres_db # O nome do banco de dados que será criado
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - pgdata:/var/lib/postgresql/data # Persistência de dados
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mongodb_data:
  pgdata:
