package presenters

import "template/internal/domain/entities"

// MapperDTOToEntity maps an EntityDTO to an Entity
func MapperDTOToEntity(dto EntityDTO) entities.Entity {
	return entities.Entity{
		Name: dto.Name,
		// The ID does not need to be set here, as it will be generated by the database
	}
}

// MapperEntityToDTO maps an EntityDTO to an Entity
func MapperEntityToDTO(entity entities.Entity) EntityDTO {
	return EntityDTO{
		Name: entity.Name,
		// The ID does not need to be set here, as it will be generated by the database
	}
}
